fix: do not clear pasted chunk clipboard
WolvenKit/WolvenKit pull request #1408
Opened 2023-10-30 10:36 UTC by rfuzzo

# do not clear pasted chunk clipboard

please check if that's a problem

Fixed:
- do not clear pasted chunk clipboard

<Additional notes>
closes #1286

2023-10-30 12:28 UTC, seberoth requested changes
Please paste a (deep)copy (if applicable) then. Else every copy will be the same reference.

2023-10-30 12:31 UTC, rfuzzo commented
ah thanks, that makes sense

2023-10-31 07:29 UTC, rfuzzo commented
Updated branch

2023-10-31 07:31 UTC, seberoth approved these changes

2023-10-31 07:32 UTC, merged