#1540 overwrite array/buffer with selection
WolvenKit/WolvenKit pull request #1551
Opened 2024-02-01 19:05 UTC by manavortex

# overwrite array/buffer with selection

**Implemented:**
- #1540

2024-02-02 06:00 UTC, seberoth requested changes

2024-02-02 06:59 UTC, manavortex commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +                if (ResolvedData is IRedBufferPointer db)
because I had no idea that exists ':D

2024-02-02 06:59 UTC, manavortex commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +        ? "Overwrite Array/Buffer with Selection"
Could you fix it up? I have no idea where to put it <3

2024-02-02 13:11 UTC, jackhumbert commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +        ? "Overwrite Array/Buffer with Selection"
I think defining two different menu items with their own visibility booleans is probably the best way, along with their own commands.

2024-02-03 17:09 UTC, rfuzzo approved these changes
manually approved PR

2024-02-03 17:10 UTC, merged