1655 fixed missing refresh after delete
WolvenKit/WolvenKit pull request #1656
Opened 2024-04-25 16:32 UTC by manavortex

closes #1655

2024-04-25 22:53 UTC, dragonzkiller commented on WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
what is this change doing? it doesn't seem to be part of the issue this PR resolves

2024-04-26 06:14 UTC, manavortex commented on WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
making buffers writable again. it's unrelated, but it's a small change, and it'll resolve an issue that sim has

2024-04-26 11:51 UTC, dragonzkiller commented on WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
I don't really like unrelated changes especially in PRs that are dedicated to closing an issue. But I'll approve it this time

2024-04-26 11:52 UTC, dragonzkiller requested changes
Resolve the conflict and I can approve

2024-04-26 12:00 UTC, dragonzkiller approved these changes

2024-04-26 12:00 UTC, merged