Optimizations  @seberoth, @WSSDude420, @WopsS
WolvenKit/Wolvenkit pull request #372
Opened 2021-02-21 16:48 UTC by rfuzzo

# cr2w optimizations

Implemented:
- multitarget cr2w, console and cyberformats

Fixed:
- cr2w optimizations
- fixed an uncooking bug

<Additional notes>
 mentions #316, @seberoth, @WSSDude420, @WopsS

2021-02-21 17:53 UTC, WopsS requested changes
Hopefully I did not miss something.

2021-02-21 17:53 UTC, WopsS commented on CP77.CR2W/Reflection/REDReflection.cs
> +        public static IEnumerable<Member> GetREDBuffers(this CVariable cvar) =>
This one should be `GetMembersInternal`.

2021-02-21 17:53 UTC, WopsS commented on WolvenKit.CR2W/Reflection/REDReflection.cs
> +                    .OrderBy(p => p.Ordinal)
`OrderBy` after `Where`.

2021-02-21 17:53 UTC, WopsS commented on WolvenKit.CR2W/Reflection/REDReflection.cs
> +                        return (attrib != null) && !(attrib is REDBufferAttribute);
Could limit it only to `attrib is not REDBufferAttribute` if you want.

2021-02-22 08:39 UTC, rfuzzo commented
don't merge yet please. I'm adding some more optimizations.

2021-02-22 10:46 UTC, rfuzzo commented
This can be reviewed and merged now.

2021-02-22 16:41 UTC, WopsS commented on CP77.CR2W/Modkit/UncookMLmask.cs
> +                tile = ms.ToArray();
Is `ToArray` necessary? Couldn't this be just a stream and you read from it instead of copy all bytes just to do one thing?

2021-02-22 20:50 UTC, WopsS approved these changes

2021-02-22 21:10 UTC, merged