First time, project wizard, settings viewmodel updates
WolvenKit/Wolvenkit pull request #373
Opened 2021-02-23 11:33 UTC by kote2ster

First time, project wizard, settings viewmodel updates

Implemented:
- Add custom handycontrol error handling style for input fields
- Add logic for input field validation on wizard windows
- Move settings vm to first time setup wizard vm
- Add first time setup wizard window
- Add create project window
- Add exe/dir validation in settings

Fixed:
- Fix settings json saving and loading

2021-02-23 11:52 UTC, Traderain requested changes
Please use more comments in the wizard classes, an xmldoc on the top is enough but at least people know what happens there. Otherwise <3

2021-02-23 11:52 UTC, Traderain commented on WolvenKit/Model/Wizards/FirstSetupWizardModel.cs
> +		/// Gets/Sets the donate link.
Comments formatting

2021-02-23 11:52 UTC, Traderain commented on WolvenKit/Services/ApplicationInitializationService.cs
> +                //_commandManager.GetCommand(AppCommands.Settings.General).SafeExecute();
Why is this commented out?

2021-02-23 11:52 UTC, Traderain commented on WolvenKit/ViewModels/Wizards/FirstSetupWizardViewModel.cs
> +            if (!TryCopyOodleLib())
Handle the error here properly, maybe filenotfoundexception or something

2021-02-23 11:52 UTC, Traderain commented on WolvenKit/ViewModels/Wizards/FirstSetupWizardViewModel.cs
> +        //private void SetDefaultModDir()
Delete these

2021-02-23 11:52 UTC, Traderain commented on WolvenKit/Views/Wizards/WizardPages/FirstSetupWizard/FinalizeSetupView.xaml.cs
> +        private async void ConfirmSettings_Click(object sender, System.Windows.RoutedEventArgs e)
Copy the picture to the project dir

2021-02-23 11:52 UTC, Traderain commented on WolvenKit/Views/Wizards/WizardPages/ProjectWizard/ProjectConfigurationView.xaml.cs
> +        private void imgSelector_Executed(object sender, System.Windows.Input.ExecutedRoutedEventArgs e)
Copy the image

2021-02-23 11:52 UTC, Traderain commented
@rfuzzo @Offline-R503B Can you guys test out the behaviour?

2021-02-23 11:53 UTC, rfuzzo commented on WolvenKit/ViewModels/Wizards/FirstSetupWizardViewModel.cs
> +        //private void SetDefaultModDir()
I can handle this in my PR

2021-02-25 08:08 UTC, Traderain approved these changes

2021-02-25 08:09 UTC, merged