Feature: Morph target imports
WolvenKit/WolvenKit pull request #579
Opened 2021-09-04 04:04 UTC by rennr

# Pull request template

Feature: Morph Target Imports

Implemented:
- Feature: Import morph targets into a .morphtarget file on exported .glb files.

Fixed:
- Fix: Exception due to in-use file no longer occurs after import followed by export or vice-versa.
- Fix: Deleting or renaming files on filesystem no longer causes exception due to tracking of the selected item in the Import/Export panel.

2021-09-04 08:06 UTC, rfuzzo approved these changes
great! thank you!

2021-09-05 00:17 UTC, rennr commented
Conflicts with master have been resolved. There was a fix regarding exceptions on filesystem changes that may have been made redundant due to changes in the master so I've removed that code. If the problem continues I will make another PR for just that.

2021-09-05 07:26 UTC, rfuzzo requested changes
Thanks! I have 2 more requests: one fails the build, the other is cosmetic. After that we can merge.

2021-09-05 07:26 UTC, rfuzzo commented on WolvenKit.Modkit/RED4/Tools/Common/Structs.cs
> +using WolvenKit.Modkit.RED4.Materials;
this using needs to be removed.

2021-09-05 07:26 UTC, rfuzzo commented on WolvenKit/Functionality/Commands/SyncFusion/SFDataGridSelectionControllerExt.cs
> +            var IEVM = Locator.Current.GetService<ImportExportViewModel>();
please remove this line, I think it came in through a bad merge

2021-09-05 16:53 UTC, rennr commented
> 
> 
> Thanks! I have 2 more requests: one fails the build, the other is cosmetic. After that we can merge.

The lines have been removed and it should build now.

2021-09-06 07:37 UTC, rfuzzo approved these changes
thank you

2021-09-06 07:37 UTC, merged