Code cleanup
WolvenKit/WolvenKit pull request #820
Opened 2022-06-08 10:28 UTC by rfuzzo

# Code cleanup

- modkit
- common
- core

2022-06-08 17:30 UTC, WopsS requested changes
The nodiscard thing like `_= ...` is it really necessary? I found it all over the place here.

In most cases I prefer normal `if-else` instead of lazy-ifs (one-line).

This is a big PR, I will stop for now. If you will not merge it until tomorrow or the weekend I can check the rest of it, but I hope you got the gist of it 🏃 .

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +                if (s != null && s.StartsWith("LocKey#") && ulong.TryParse(s[7..], out var locKey))
```suggestion
                if (s is not null && s.StartsWith("LocKey#") && ulong.TryParse(s[7..], out var locKey))
```

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +                        if (s != null && s.StartsWith("LocKey#") && ulong.TryParse(s[7..], out _))
```suggestion
                        if (s is not null && s.StartsWith("LocKey#") && ulong.TryParse(s[7..], out _))
```

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +                    if (Value != null && Value.StartsWith("LocKey#") && ulong.TryParse(Value[7..], out var key))
```suggestion
                    if (Value is not null && Value.StartsWith("LocKey#") && ulong.TryParse(Value[7..], out var key))
```

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +                if (s != null && s.StartsWith("LocKey#") && ulong.TryParse(s[7..], out var locKey2))
```suggestion
                if (s is not null && s.StartsWith("LocKey#") && ulong.TryParse(s[7..], out var locKey2))
```

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> +                return PropertyType.IsAssignableTo(typeof(WorldTransform))
Please don't do this.

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.App/ViewModels/Tools/TweakBrowserViewModel.cs
> +        private string _searchText = "";
```suggestion
        private string _searchText = string.Empty;
```

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.Common/RED4/CR2W/JSON/PrimitiveConverter.cs
>                  }
2600+ lines of code, I would really split this file into multiple ones.

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.Common/Services/HashService.cs
> +            return _additionalhashes.ContainsKey(key) ? _additionalhashes[key].ToString() : "";
```suggestion
            return _additionalhashes.ContainsKey(key) ? _additionalhashes[key].ToString() : string.Empty;
```

Again, I would prefer the old `if-else`.

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.Core/CRC/Crc32Algorithm.cs
> +        public static uint Append(uint initial, byte[] input, int offset, int length) => input == null
This is hard to read.

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.Core/CRC/Crc32CAlgorithm.cs
> +        public static uint Append(uint initial, byte[] input, int offset, int length) => input == null
Hard to read.

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.Core/Compression/Oodle.cs
> +            result = RuntimeInformation.IsOSPlatform(OSPlatform.OSX)
Hard to read.

2022-06-08 17:30 UTC, WopsS commented on WolvenKit.Core/Extensions/StringExtensions.cs
> +            isDLC = relativePath.StartsWith("DLC\\") || (relativePath.StartsWith("Mod\\") ? false : throw new NotImplementedException());
Kind of hard to read.

2022-06-08 18:12 UTC, rfuzzo commented on WolvenKit.App/Models/WKPackage.cs
> +#pragma warning disable IDE0078 // Use pattern matching
Because it doesn't compile if VS applies the code cleanup lol

2022-06-08 18:13 UTC, rfuzzo commented on WolvenKit.App/Services/ISettingsManager.cs
> +        //public string CP77GameDirPath { get; set; }
should be removed 👍

2022-06-08 18:21 UTC, seberoth commented on WolvenKit.App/Services/SettingsManager.cs
> +            return fi.Directory is { Parent.Parent: { } }
fi.Directory != null && fi.Directory.Parent != null && fi.Directory.Parent.Parent != null

2022-06-09 10:24 UTC, rfuzzo commented on WolvenKit.App/Controllers/MockGameController.cs
>      public class MockGameController : IGameController
no it's used when no wkit project is loaded

2022-06-09 10:33 UTC, rfuzzo commented on WolvenKit.App/Extensions/TreeExtensions.cs
> +                var rootData = lookup.Count == 1 ? lookup.First().Key : default;
T cannot be made nullable here

2022-06-09 10:34 UTC, rfuzzo commented on WolvenKit.App/Functionality/Extensions/SharpDXExtensions.cs
> +        public static SharpDX.Vector2 ToVector2(this System.Numerics.Vector2 v) => new(v.X, v.Y);
no, HelixToolkit only takes DXVectors...

2022-06-09 10:35 UTC, rfuzzo commented on WolvenKit.App/Functionality/Other/ImageDecoder.cs
> +                _ = stream.Seek(0, SeekOrigin.Begin);
removed 👍

2022-06-09 10:39 UTC, rfuzzo commented on WolvenKit.App/Helpers/GlobalHelper.cs
>      public enum EAnimals
😂

2022-06-09 10:53 UTC, seberoth commented on WolvenKit.App/Extensions/TreeExtensions.cs
> +                var rootData = lookup.Count == 1 ? lookup.First().Key : default;
Doesn't matter, does it? Since `??` would set it to default if the `lookup.FirstOrDefault()?.Key` is null

2022-06-09 11:02 UTC, rfuzzo commented on WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
> +        public ulong ChunkMask { get; set; } = 18446744073709551615;
for ulong that's not -1?

2022-06-09 11:14 UTC, WopsS commented on WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
> +        public ulong ChunkMask { get; set; } = 18446744073709551615;
Oh, is it not possible to write -1 to make it overflow in C#?

2022-06-09 11:19 UTC, rfuzzo commented on WolvenKit.Common/DDS/DDSUtils.cs
> +        private static uint MAKEFOURCC(char ch0, char ch1, char ch2, char ch3) => (uint)(ch0 | (ch1 << 8) | (ch2 << 16) | (ch3 << 24));
WHATDOYOUWANTINSTEAD?

2022-06-09 11:21 UTC, WopsS commented on WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
> +        public ulong ChunkMask { get; set; } = 18446744073709551615;
Oh, it was `ulong.MaxValue`.

2022-06-09 11:26 UTC, seberoth commented on WolvenKit.Common/DDS/DDSUtils.cs
> +        private static uint MAKEFOURCC(char ch0, char ch1, char ch2, char ch3) => (uint)(ch0 | (ch1 << 8) | (ch2 << 16) | (ch3 << 24));
MAOAM

2022-06-09 12:35 UTC, closed without merging